version: '3.1'

services:
  mongo:
    image: mongo
    container_name: study-manager-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: study-manager
      TZ: Asia/Tokyo
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongodb/db:/data/db
      - ./docker/mongodb/init.d:/docker-entrypoint-initdb.d